#!/bin/bash
xcode-select --install
read
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

## Provisioning

brew cask install openzfs
brew tap caskroom/versions
brew tap homebrew/versions

brew cask install sublime-text3
brew cask install virtualbox
brew cask install virtualbox-extension-pack

brew cask install packer
brew cask install vagrant

brew cask install google-chrome
brew install homebrew/dupes/rsync
brew install python3
brew install python
brew cask install xquartz
brew cask install steam
brew cask install alfred
brew cask install iterm2
brew cask install atom

pip install ansible

# git clone git://github.com/ansible/ansible.git --recursive
# cd ./ansible

# source ./hacking/env-setup
# sudo easy_install pip
#sudo pip install paramiko PyYAML Jinja2 httplib2 six
# sudo pip install ansible

# git pull --rebase
# git submodule update --init --recursive
